- type: replace  
  path: /product-properties/.properties.system_blobstore?
  value:
    value: external_gcs_service_account
- type: replace  
  path: /product-properties/.properties.system_blobstore.external_gcs_service_account.buildpacks_bucket?
  value:
    value: ${buildpacks_bucket}
- type: replace  
  path: /product-properties/.properties.system_blobstore.external_gcs_service_account.droplets_bucket?
  value:
    value: ${droplets_bucket}
- type: replace  
  path: /product-properties/.properties.system_blobstore.external_gcs_service_account.resources_bucket?
  value:
    value: ${resources_bucket}
- type: replace  
  path: /product-properties/.properties.system_blobstore.external_gcs_service_account.packages_bucket?
  value:
    value: ${packages_bucket}
- type: replace  
  path: /product-properties/.properties.system_blobstore.external_gcs_service_account.backup_bucket?
  value:
    value: ${backup_bucket}
- type: replace  
  path: /product-properties/.properties.system_blobstore.external_gcs_service_account.project_id?
  value:
    value: ${project}
- type: replace  
  path: /product-properties/.properties.system_blobstore.external_gcs_service_account.service_account_email?
  value:
    value: ${service_account_email}
- type: replace  
  path: /product-properties/.properties.system_blobstore.external_gcs_service_account.service_account_json_key?
  value:
    value: ${service_account_key}