az-configuration:
{{range .azs}}
- name: {{.}}
{{end}}
properties-configuration:
  director_configuration:
    ntp_servers_string: 169.254.169.254
  iaas_configuration:
    auth_json: {{ toJson .opsman_service_account_key }}
    default_deployment_tag: {{.vm_tag}}
    project: {{.project}}
{{if index . "terraforming_ca_cert"}}
  security_configuration:
    trusted_certificates: |
{{indent 6 .terraforming_ca_cert}}
{{end}}
network-assignment:
  network:
    name: {{.infrastructure_subnet_name}}
  singleton_availability_zone:
    name: {{index .azs 0}}
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: {{.infrastructure_subnet_name}}
    subnets:
    - availability_zone_names:
      {{range .azs}}
      - {{.}}
      {{end}}
      cidr: {{.infrastructure_subnet_cidr}}
      dns: 169.254.169.254
      gateway: {{.infrastructure_subnet_gateway}}
      iaas_identifier: {{.network_name}}/{{.infrastructure_subnet_name}}/{{.region}}
      reserved_ip_ranges: {{cidrhost (.infrastructure_subnet_cidr) 0}}-{{cidrhost (.infrastructure_subnet_cidr) 4}}
  - name: {{.pas_subnet_name}}
    subnets:
    - availability_zone_names:
      {{range .azs}}
      - {{.}}
      {{end}}
      cidr: {{.pas_subnet_cidr}}
      dns: 169.254.169.254
      gateway: {{.pas_subnet_gateway}}
      iaas_identifier: {{.network_name}}/{{.pas_subnet_name}}/{{.region}}
      reserved_ip_ranges: {{cidrhost (.pas_subnet_cidr) 0}}-{{cidrhost (.pas_subnet_cidr) 4}}
  - name: {{.services_subnet_name}}
    subnets:
    - availability_zone_names:
      {{range .azs}}
      - {{.}}
      {{end}}
      cidr: {{.services_subnet_cidr}}
      dns: 169.254.169.254
      gateway: {{.services_subnet_gateway}}
      iaas_identifier: {{.network_name}}/{{.services_subnet_name}}/{{.region}}
      reserved_ip_ranges: {{cidrhost (.services_subnet_cidr) 0}}-{{cidrhost (.services_subnet_cidr) 4}}
resource-configuration:
  compilation:
    instance_type:
      id: xlarge.disk
