---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfinfrastructure/releng-tools

inputs:
- name: paving-ci
- name: env-state

run:
  path: paving-ci/ci/tasks/custom-vm-extensions/task.sh

params:
  OM_USERNAME:
  OM_PASSWORD:
  PRODUCT:
