product-name: pivotal-mysql
product-properties:
  .properties.plan1_selector.single_node.az_multi_select:
    value: [${plan_azs}]
  .properties.plan2_selector.single_node.az_multi_select:
    value: [${plan_azs}]
  .properties.plan3_selector.single_node.az_multi_select:
    value: [${plan_azs}]
  .properties.syslog_migration_selector:
    value: disabled
  .properties.backups_selector:
    value: SCP Backups
  .properties.backups_selector.scp.user:
    value: 'none'
  .properties.backups_selector.scp.key:
    value:
      secret: 'none'
  .properties.backups_selector.scp.server:
    value: 'none'
  .properties.backups_selector.scp.destination:
    value: 'none'
  .properties.backups_selector.scp.port:
    value: '1234'
  .properties.backups_selector.scp.cron_schedule:
    value: 0 0 5 31 2 ?
  .properties.global_recipient_email:
    value: none@localhost
  .properties.deprecated_bindings_string:
    value: X
network-properties:
  network:
    name: pas
  service_network:
    name: services
  other_availability_zones: ${az_configuration}
  singleton_availability_zone:
    name: ${az}