product-name: cf
product-properties:
  .cloud_controller.system_domain:
    value: ${sys_domain}
  .cloud_controller.apps_domain:
    value: ${apps_domain}
  .ha_proxy.skip_cert_verify:
    value: true
  .properties.haproxy_forward_tls:
    value: disable
  .properties.security_acknowledgement:
    value: X
  .mysql_monitor.recipient_email:
    value: nobody@localhost
  .properties.credhub_internal_provider_keys:
    value:
    - name: default
      primary: true
      key:
        secret: askdnasoidansfiopanskflasf
  .properties.networking_poe_ssl_certs:
    value:
    - certificate:
        cert_pem: ${tls_cert}
        private_key_pem: ${tls_private_key}
      name: default
  .uaa.service_provider_key_credentials:
    value:
      cert_pem: ${tls_cert}
      private_key_pem: ${tls_private_key}
network-properties:
  network:
    name: pas
  other_availability_zones: ${az_configuration}
  singleton_availability_zone:
    name: ${az}
resource-config:
  control:
    elb_names: [${ssh_elb_names}]
  router:
    elb_names: [${web_elb_names}]
  compute:
    instances: ${compute_instances}
  blobstore:
    instances: 0
errand-config:
  smoke_tests:
    post-deploy-state: ${run_smoke_tests}
  test-autoscaling:
    post-deploy-state: ${run_smoke_tests}