product-name: p-redis
product-properties:
  .properties.plan_collection:
    value:
    - az_multi_select: [${plan_azs}]
      cf_service_access: enable
      description: This plan provides a test on-demand Redis instance, tailored for
        caching use-cases with persistence to disk enabled
      instance_limit: 20
      lua_scripting: false
      maxclients: 1000
      name: on-demand-cache
      tcp_keepalive: 60
      timeout: 3600
network-properties:
  network:
    name: pas
  service_network:
    name: services
  other_availability_zones: ${az_configuration}
  singleton_availability_zone:
    name: ${az}
errand-config:
  smoke-tests:
    post-deploy-state: ${run_smoke_tests}
  on-demand-broker-smoke-tests:
    post-deploy-state: ${run_smoke_tests}