product-name: p-redis
product-properties:
  .properties.syslog_selector:
    value: 'No'
  .properties.small_plan_selector.active.az_multi_select:
    value:
    - ${az}
  .properties.medium_plan_selector.active.az_multi_select:
    value:
    - ${az}
  .properties.large_plan_selector.active.az_multi_select:
    value:
    - ${az}
network-properties:
  network:
    name: pas
  service_network:
    name: services
  other_availability_zones: ${az_configuration}
  singleton_availability_zone:
    name: ${az}