product-name: p-dataflow
network-properties:
  network:
    name: pas
  service_network:
    name: services
  other_availability_zones: ${az_configuration}
  singleton_availability_zone:
    name: ${az}
product-properties:
  .properties.dataflow_messaging_service:
    value: p.rabbitmq
  .properties.dataflow_messaging_plan:
    value: single-node-3.7