---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfinfrastructure/releng-tools

inputs:
- name: env-state
- name: paving-ci

run:
  path: paving-ci/ci/tasks/configure-authentication/task

params:
  OM_USERNAME:
  OM_PASSWORD:
