name: 'CI'
on:
  - pull_request
  - push
  
jobs:
  format:
    name: 'Format'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5
      - name: 'Terraform Format'
        run: terraform fmt -check -recursive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  aws:
    name: 'AWS'
    needs: format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['2.9', '2.10']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5
      - name: 'Terraform Init'
        working-directory: ci/aws
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}