name: 'CI'
on:
  - pull_request
  - push

jobs:
  format:
    name: 'Format'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5
      - name: 'Terraform Format'
        run: terraform fmt -check -recursive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  aws:
    name: 'AWS'
    needs: format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['2.9', '2.10']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5
      - name: 'Terraform Init'
        working-directory: ci/aws
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit Short SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: 'Terraform Plan'
        working-directory: ci/aws
        run: terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_pivnet_token: ${{ secrets.PIVNET_TOKEN }}
          TF_VAR_pas_version: ${{ matrix.version }}
          TF_VAR_environment_name: ${{ env.SHORT_SHA }}